### ISSUE TITLE
XEM6010-LX45 replacement?

### ISSUE THREAD

**Issue by fanmingyu212** [Jayich-Lab/pulse_sequencer#1]
XEM6010-LX150 and XEM6310-LX150 should both be compatible with the footprint, and they all use the same chip (XC6S). The LX150 has more RAM and slices than LX45, while the XEM6310 supports USB 3.0 (XEM6010 supports 2.0).

Can the above serve as "drop in" replacements of the current FPGA? Can they provide benefits such as longer pulse sequence, more timetags and photon counts per readout, and faster programming / readout of the pulser?

**Comment by fanmingyu212** [comment]
The software to program and to build binary file for XEM6010/6310 (Spartan 6) is free (Xilinx ISE). It seems not too hard to make changes to enable features such as more timetags and more photon counts per readout. Supports for USB 3.0 seems doable too. To make the pulse sequence longer, both the XEM board code and the DDS board (See #2) code need to be modified though. Could be doable since the software for programming the DDS board (Cyclone IV, Intel Quartus Prime Lite Edition) is also free.

**Comment by fanmingyu212** [comment]
Another advantage of XEM6310 over 6010 is that the 6310 has a low-jitter clock. The stability is improved from 100 ppm to 50 ppm, and the jitter from 400 ps (200 MHz) to <1 ps (100 MHz). The stability and jitter influences pulse sequence and photon timings, but not affect the frequency / phase of the DDSes.

**Comment by jayich** [comment]
Hardware that is no longer used by the lab.
