### ISSUE TITLE
DDS board upgrade

### ISSUE THREAD

**Issue by fanmingyu212** [Jayich-Lab/pulse_sequencer#2]
Currently the DDS boards support sine waveform with frequency / amplitude ramping. Some improvements that could be helpful include: 
 - Faster programming of the DDS chip and the VGA, as some commands lag ~1 us, see https://aip.scitation.org/doi/full/10.1063/1.4935476 for details.
 - Arbitrary waveform generation

**Comment by jayich** [comment]
Hardware that is no longer used by the lab.
